<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  Visual Studio 2015
     Created on:         4/19/2018 4:57 AM
     Generated by:       http://vcloud-lab.com
     Written by:         Kunal Udapi
     Tested on:          Windows 10
                         Windows 2016 Server
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated using Visual Studio 2015
#>

Add-Type -AssemblyName PresentationFramework

$RawXamlForm = @"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        Title="Configure Proxy Server" Height="201" Width="525" ResizeMode="NoResize" Topmost="True" WindowStyle="none">
    <Window.Background>
        <LinearGradientBrush EndPoint="0.5,1" StartPoint="0.5,0">
            <GradientStop Color="Black" Offset="0"/>
            <GradientStop Color="#FF4E7645" Offset="1"/>
        </LinearGradientBrush>
    </Window.Background>
    <Grid>
        <Label x:Name="CurrentProxyLabel" Content="Current Internet Proxy configuration" HorizontalAlignment="Left" Margin="10,10,0,0" VerticalAlignment="Top" Width="225" Foreground="White" FontStyle="Italic" FontWeight="Bold"/>
        <Label x:Name="CProxyStatusLabel" HorizontalAlignment="Left" Margin="235,10,0,0" VerticalAlignment="Top" Width="140" Foreground="#FFFF0C00" HorizontalContentAlignment="Right" Height="26"/>
        <Label x:Name="UrlLabel" Content="http://vcloud-lab.com" HorizontalAlignment="Left" Margin="248,159,0,0" VerticalAlignment="Top" Width="127" Foreground="White"/>
        <TextBox x:Name="CProxyServerBox" HorizontalAlignment="Left" Height="23" Margin="10,36,0,0" TextWrapping="Wrap" Text="Current Proxy Server" VerticalAlignment="Top" Width="270" Background="#FF3C4632" Foreground="White" IsReadOnly="True"/>
        <TextBox x:Name="CProxyPortBox" HorizontalAlignment="Left" Height="23" Margin="285,36,0,0" TextWrapping="Wrap" Text="Port" VerticalAlignment="Top" Width="90" Background="#FF3C4632" Foreground="White" IsReadOnly="True"/>
        <Button x:Name="RefreshB" Content="Refresh" HorizontalAlignment="Left" Margin="285,64,0,0" VerticalAlignment="Top" Width="90" Height="24"/>
        <Label x:Name="NewProxyLabel" Content="Change new Internet Proxy server and port below" HorizontalAlignment="Left" Margin="10,82,0,0" VerticalAlignment="Top" Width="440" Foreground="White" FontWeight="Bold" FontSize="14"/>
        <Label x:Name="NewProxyServerlabel" Content="New Proxy Server" HorizontalAlignment="Left" Margin="10,105,0,0" VerticalAlignment="Top" Width="125" Foreground="White" FontStyle="Italic"/>
        <Label x:Name="NewProxyPortlabel" Content="New Proxy Port" HorizontalAlignment="Left" Margin="280,105,0,0" VerticalAlignment="Top" Width="95" Foreground="White" FontStyle="Italic"/>
        <TextBox x:Name="ChangeProxyServer" Text='Type Valid Proxy server and Port no' HorizontalAlignment="Left" Height="23" Margin="10,131,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="270" Background="#FFB4DC5A" Foreground="Black" IsReadOnly="True"/>
        <TextBox x:Name="ChangeProxyPort" Text='808' HorizontalAlignment="Left" Height="23" Margin="285,131,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="90" Background="#FFB4DC5A" Foreground="Black" IsReadOnly="True"/>
        <Button x:Name="ChangeProxyB" Content="Change Proxy" HorizontalAlignment="Left" Margin="380,131,0,0" VerticalAlignment="Top" Width="127" Height="24" IsEnabled="False"/>
        <Image x:Name="LogoImage" HorizontalAlignment="Left" Height="101" Margin="388,15,0,0" VerticalAlignment="Top" Width="119"/>
        <CheckBox x:Name="EnableProxy" Content="Enable or Disable Proxy" HorizontalAlignment="Left" Margin="15,164,0,0" VerticalAlignment="Top" Width="150" Foreground="White" IsChecked="True"/>
        <Button x:Name="CloseB" Content="Close Utility" HorizontalAlignment="Left" Margin="380,161,0,0" VerticalAlignment="Top" Width="127" Height="24"/>
    </Grid>
</Window>
"@

$RawXamlForm = $RawXamlForm -replace 'x:', ''
[xml]$XamlForm = $RawXamlForm
$XMLReader = (New-Object System.Xml.XmlNodeReader $XamlForm)
$ChangeProxyForm = [Windows.Markup.XamlReader]::Load($XMLReader)
$XamlForm.SelectNodes("//*[@Name]") | Foreach-Object {Set-Variable -Name ($_.Name) -Value $ChangeProxyForm.FindName($_.Name)}

#'HKEY_USERS\S-1-5-21-3215338630-3058045017-314744653-1000\Software\Microsoft\Windows\CurrentVersion\Internet Settings'
#'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings'
#'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings'

function Disable-Change {
    $ChangeProxyServer.IsReadOnly = $true
    $ChangeProxyPort.IsReadOnly = $true
    $ChangeProxyB.IsEnabled = $false
    $EnableProxy.IsEnabled = $false
}
function Enable-Change {
    $ChangeProxyServer.IsReadOnly = $false
    $ChangeProxyPort.IsReadOnly = $false
    $ChangeProxyB.IsEnabled = $true
    $EnableProxy.IsEnabled = $true
}

function Get-CurrentProxyInfo {
    try {
        $Script:CurrentInternetProxyInfo = Get-ItemProperty -Path $RegKey -ErrorAction Stop
        $CurrentProxyInfo = $Script:CurrentInternetProxyInfo.ProxyServer -split ':'
        Switch ($Script:CurrentInternetProxyInfo.ProxyEnable) {
           0 {$CProxyStatusLabel.Content = 'Proxy is Disabled'}
           1 {$CProxyStatusLabel.Content = 'Proxy is Enabled'}
           default {$CProxyStatusLabel.Content = 'Unknown Setting'}
        }
        $CProxyServerBox.Text = $CurrentProxyInfo[0]
        $CProxyPortBox.Text = $CurrentProxyInfo[1]
        Enable-Change
    }
    catch {
        $CProxyServerBox.Text = "You don't have permissions to read registry"
        Disable-Change
    }
}
Function Set-NewProxyConfiguration {
    if ($ChangeProxyPort.Text -match '\d' -and $ChangeProxyServer.Text -ne 'Type Valid Proxy server and Port no') {
        try {
            Switch ($EnableProxy.IsChecked) {
                True {Set-ItemProperty -Path $RegKey -Name ProxyEnable -Value 1 -ErrorAction Stop}
                False {Set-ItemProperty -Path $RegKey -Name ProxyEnable -Value 0 -ErrorAction Stop}
            }
            $NewProxy = "{0}:{1}" -f $ChangeProxyServer.Text, $ChangeProxyPort.Text
            Set-ItemProperty -Path $RegKey -Name ProxyServer -Value $NewProxy -ErrorAction Stop
        }
        catch {
            $ChangeProxyServer.Text = "You don't have permissions to read registry"
            Disable-Change
        }
    }

    Get-CurrentProxyInfo
}

Try {
    $Path = Split-Path $MyInvocation.MyCommand.Path -Parent -ErrorAction Stop
    $LogoImage.Source = "$Path\Proxy_Change.png"
}
Catch {
    
}
$RegKey = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings'
$UrlLabel.Add_MouseDoubleClick({[system.Diagnostics.Process]::start('http://vcloud-lab.com')})
$CloseB.Add_Click({$ChangeProxyForm.Close()})
$RefreshB.Add_Click({Get-CurrentProxyInfo})
Get-CurrentProxyInfo
$ChangeProxyB.Add_Click({Set-NewProxyConfiguration})

$ChangeProxyForm.Add_MouseDown({$ChangeProxyForm.DragMove()}) 
[void]$ChangeProxyForm.ShowDialog()
#ProxyEnable = 1  #1 = enabled & 0 = Disabled
#ProxyServer = 'OldProxyServer:808'
